#=========================================================================
# Custom Scripts -- signoff
#=========================================================================

name: custom-signoff-extract-block-pg

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - generate-results.tcl

